import Navbar from "@/components/navbar";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Eleonetech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="fr" className="dark">
        <body className={montserrat.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
